<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="11588" started-at="2021-07-20T12:28:00 IST" finished-at="2021-07-20T12:28:11 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="11588" started-at="2021-07-20T12:28:00 IST" finished-at="2021-07-20T12:28:11 IST">
      <class name="com.accenture.testcases.TC_001_Testcase1">
        <test-method status="PASS" signature="setUpReport()[pri:0, instance:com.accenture.testcases.TC_001_Testcase1@42f93a98]" name="setUpReport" is-config="true" duration-ms="215" started-at="2021-07-20T12:28:00 IST" finished-at="2021-07-20T12:28:00 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpReport -->
        <test-method status="PASS" signature="openBrowser()[pri:0, instance:com.accenture.testcases.TC_001_Testcase1@42f93a98]" name="openBrowser" is-config="true" duration-ms="5939" started-at="2021-07-20T12:28:00 IST" finished-at="2021-07-20T12:28:06 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method status="FAIL" signature="loginAsAdmin()[pri:2, instance:com.accenture.testcases.TC_001_Testcase1@42f93a98]" name="loginAsAdmin" duration-ms="4159" started-at="2021-07-20T12:28:06 IST" finished-at="2021-07-20T12:28:10 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login failed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login failed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.accenture.pages.LoginPage.loginToApplication(LoginPage.java:36)
at com.accenture.testcases.TC_001_Testcase1.loginAsAdmin(TC_001_Testcase1.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAsAdmin -->
        <test-method status="PASS" signature="tearDownReport(org.testng.ITestResult)[pri:0, instance:com.accenture.testcases.TC_001_Testcase1@42f93a98]" name="tearDownReport" is-config="true" duration-ms="562" started-at="2021-07-20T12:28:10 IST" finished-at="2021-07-20T12:28:11 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginAsAdmin status=FAILURE method=TC_001_Testcase1.loginAsAdmin()[pri:2, instance:com.accenture.testcases.TC_001_Testcase1@42f93a98] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownReport -->
        <test-method status="SKIP" signature="logoutFromApplication()[pri:2, instance:com.accenture.testcases.TC_001_Testcase1@42f93a98]" name="logoutFromApplication" duration-ms="0" started-at="2021-07-20T12:28:11 IST" depends-on-methods="com.accenture.testcases.TC_001_Testcase1.loginAsAdmin" finished-at="2021-07-20T12:28:11 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_001_Testcase1.logoutFromApplication()[pri:2, instance:com.accenture.testcases.TC_001_Testcase1@42f93a98] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_001_Testcase1.logoutFromApplication()[pri:2, instance:com.accenture.testcases.TC_001_Testcase1@42f93a98] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApplication -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.accenture.testcases.TC_001_Testcase1@42f93a98]" name="closeBrowser" is-config="true" duration-ms="834" started-at="2021-07-20T12:28:11 IST" finished-at="2021-07-20T12:28:11 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.accenture.testcases.TC_001_Testcase1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
